package woowacourse.kanban.board

import androidx.compose.ui.graphics.Color

enum class CustomColor(
    val color: Color,
) {
    CARD_BORDER(Color(0xFFE5E7EB)),
    DIVIDER(Color(0xFFF3F4F6)),
    TITLE(Color(0xFF101828)),
    SCRIPT(Color(0xFF4A5565)),
    TAG_BACKGROUND(Color(0xFFF3F4F6)),
    DEFAULT_TEXT_COLOR(Color(0xFF364153)),
    PROFILE_NICKNAME(Color(0xff364153)),
    TEXT_INPUT_ERROR_BORDER_COLOR(Color(0xFFB3261E)),
    TEXT_INPUT_DEFAULT_BORDER_COLOR(Color(0xFFAAAAAA)),
    GRAY_TEXT_COLOR(Color(0xFF0A0A0A)),
    SELECTED_BUTTON_BORDER_AND_TEXT_COLOR(Color(0xFF1447E6)),
    SELECTED_BUTTON_BACKGROUND_COLOR(Color(0xFFEFF6FF)),
    CREATE_NEW_TASK_BUTTON_COLOR(Color(0xFF4F39F6)),
    TODO_CARD_HOLDER_HEADER_COLOR(Color(0xFF155DFC)),
    IN_PROGRESS_CARD_HOLDER_HEADER_COLOR(Color(0xFFE17100)),
    DONE_CARD_HOLDER_HEADER_COLOR(Color(0xFF00A63E)),
    TODO_CARD_HOLDER_BACKGROUND_COLOR(Color(0xFFEFF6FF)),
    IN_PROGRESS_CARD_HOLDER_BACKGROUND_COLOR(Color(0xFFFFFBEB)),
    DONE_CARD_HOLDER_BACKGROUND_COLOR(Color(0xFFF0FDF4)),
    TODO_CARD_HOLDER_BORDER_COLOR(Color(0xFFBEDBFF)),
    IN_PROGRESS_CARD_HOLDER_BORDER_COLOR(Color(0xFFFEE685)),
    DONE_CARD_HOLDER_BORDER_COLOR(Color(0xFFB9F8CF)),
}
